CREATE DATABASE mato;
USE mato;

CREATE TABLE `user` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(255) NOT NULL,
  `katasandi` VARCHAR(255) NOT NULL,
  `nama` VARCHAR(255),
  `foto` VARCHAR(255),
  `birthDate` VARCHAR(255),
  `alamat` VARCHAR(255),
  `kontak` VARCHAR(50),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `turnamen` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `judul` VARCHAR(255),
  `deskripsi` LONGTEXT,
  `author` VARCHAR(255),
  `lokasi` VARCHAR(255),
  `foto` VARCHAR(255),
  `biaya_pendaftaran` VARCHAR(255),
  `date` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `blog` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `judul` VARCHAR(255),
  `deskripsi` LONGTEXT,
  `author` VARCHAR(255),
  `foto` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);